### ISSUE TITLE
Options not available in Admin Menu

### ISSUE THREAD

**Issue by Estar1** [IDeliverable/IDeliverable.Seo#3]
Hi, I've downloaded and installed the module. The features, especially the Sitemap looks very promising.
The problem is non of the features appears on the Admin Menu. We've executed all of the recipes but we can see the options appearing and a bit stuck at the moment.

**Comment by Estar1** [comment]
I've been able to resolve this now. The extracted zip file needed to be renamed correctly by removing the orchard version suffix

**Comment by eroomeoj94** [comment]
I'm getting the same issue. Does the folder need to be renamed to _IDeliverable.Seo_?
As that is fixing it for me.
